import type { ShopCategory, ShopItem } from "./types";

export const SHOP_CATEGORIES: Record<
  ShopCategory,
  { label: string; icon: string; description: string }
> = {
  charm: {
    label: "Encanto",
    icon: "💖",
    description: "Sube atracción y química",
  },
  desire: {
    label: "Deseo",
    icon: "🔥",
    description: "Sube deseo y tensión",
  },
  recovery: {
    label: "Recuperación",
    icon: "💪",
    description: "Restaura resistencia o rescata una mala jugada",
  },
  gear: {
    label: "Equipamiento",
    icon: "🎒",
    description: "Items permanentes para tu inventario",
  },
};

export const SHOP_ITEMS: ShopItem[] = [
  // ─── ENCANTO (atracción + química) ─────────────────────────────
  {
    id: "perfume",
    name: "Perfume",
    icon: "🌹",
    price: 25,
    description: "Una fragancia irresistible",
    effect: "+35 atracción",
    statEffects: { attraction: 35 },
    consumable: true,
    category: "charm",
    cooldownTurns: 3,
  },
  {
    id: "chocolates",
    name: "Chocolates finos",
    icon: "🍫",
    price: 15,
    description: "Un detalle dulce y pensado",
    effect: "+35 química",
    statEffects: { chemistry: 35 },
    consumable: true,
    category: "charm",
    cooldownTurns: 2,
  },
  {
    id: "bouquet",
    name: "Ramo de flores",
    icon: "💐",
    price: 22,
    description: "Funciona con la romántica. Cliché para la cínica.",
    effect: "+35 química, +10 atracción",
    statEffects: { chemistry: 35, attraction: 10 },
    consumable: true,
    category: "charm",
    cooldownTurns: 4,
  },
  {
    id: "gourmet_coffee",
    name: "Café gourmet",
    icon: "☕",
    price: 18,
    description: "Para conversaciones largas. Le encanta a la intelectual.",
    effect: "+30 química, +20 resistencia",
    statEffects: { chemistry: 30, stamina: 20 },
    consumable: true,
    category: "charm",
    cooldownTurns: 3,
  },
  {
    id: "book",
    name: "Libro que ella ama",
    icon: "📖",
    price: 35,
    description: "Investigaste qué le gusta. Para la intelectual o misteriosa.",
    effect: "+25 atracción, +25 química",
    statEffects: { attraction: 25, chemistry: 25 },
    consumable: true,
    category: "charm",
    cooldownTurns: 5,
  },
  {
    id: "playlist_card",
    name: "Playlist personalizada",
    icon: "🎵",
    price: 25,
    description: "Canciones elegidas para ella. Sensible y específico.",
    effect: "+20 atracción, +20 química",
    statEffects: { attraction: 20, chemistry: 20 },
    consumable: true,
    category: "charm",
    cooldownTurns: 4,
  },
  {
    id: "premium_cocktail",
    name: "Cóctel premium",
    icon: "🍸",
    price: 28,
    description: "Para la fiestera. Para la sofisticada.",
    effect: "+20 deseo, +20 atracción",
    statEffects: { desire: 20, attraction: 20 },
    consumable: true,
    category: "charm",
    cooldownTurns: 3,
  },

  // ─── DESEO (deseo + tensión) ──────────────────────────────────
  {
    id: "wine",
    name: "Vino tinto",
    icon: "🍷",
    price: 18,
    description: "Una botella para soltar inhibiciones",
    effect: "+30 deseo, +10 tensión",
    statEffects: { desire: 30, tension: 10 },
    consumable: true,
    category: "desire",
    cooldownTurns: 2,
  },
  {
    id: "candles",
    name: "Velas aromáticas",
    icon: "🕯️",
    price: 18,
    description: "Crea el ambiente perfecto",
    effect: "+25 tensión, +15 química",
    statEffects: { tension: 25, chemistry: 15 },
    consumable: true,
    category: "desire",
    cooldownTurns: 3,
  },
  {
    id: "cigarette",
    name: "Cigarrillo compartido",
    icon: "🚬",
    price: 8,
    description: "Cliché con onda. Funciona con la rebelde.",
    effect: "+25 tensión, +10 deseo",
    statEffects: { tension: 25, desire: 10 },
    consumable: true,
    category: "desire",
    cooldownTurns: 2,
  },
  {
    id: "aphrodisiac_fruits",
    name: "Frutas afrodisíacas",
    icon: "🍓",
    price: 35,
    description: "Fresas, miel, champaña. Casi sin sutileza.",
    effect: "+35 deseo, +20 tensión",
    statEffects: { desire: 35, tension: 20 },
    consumable: true,
    category: "desire",
    cooldownTurns: 4,
  },
  {
    id: "hard_drink",
    name: "Trago fuerte",
    icon: "🥃",
    price: 22,
    description: "Whisky doble. Riesgo: agota.",
    effect: "+35 deseo, -15 resistencia",
    statEffects: { desire: 35, stamina: -15 },
    consumable: true,
    category: "desire",
    cooldownTurns: 3,
  },
  {
    id: "massage_oil",
    name: "Aceite de masaje",
    icon: "💆",
    price: 30,
    description: "Para descubrir su cuerpo despacio.",
    effect: "+30 tensión, +25 deseo",
    statEffects: { tension: 30, desire: 25 },
    consumable: true,
    category: "desire",
    cooldownTurns: 4,
  },

  // ─── RECUPERACIÓN (stamina + rescue) ──────────────────────────
  {
    id: "energy_shot",
    name: "Bebida energética",
    icon: "⚡",
    price: 20,
    description: "Para mantener el ritmo toda la noche",
    effect: "+45 resistencia",
    statEffects: { stamina: 45 },
    consumable: true,
    category: "recovery",
    cooldownTurns: 2,
  },
  {
    id: "sincere_apology",
    name: "Disculpas con detalle",
    icon: "🤝",
    price: 35,
    description: "Cuando metiste la pata. Solo usá si la cagaste.",
    effect: "+40 atracción",
    statEffects: { attraction: 40 },
    consumable: true,
    category: "recovery",
    cooldownTurns: 6,
  },
  {
    id: "second_chance",
    name: "Segunda oportunidad",
    icon: "🎲",
    price: 60,
    description: "Recupera todo de golpe cuando estás al borde del desastre.",
    effect: "+25 a todas las stats",
    statEffects: {
      attraction: 25,
      desire: 25,
      tension: 25,
      stamina: 25,
      chemistry: 25,
    },
    consumable: true,
    category: "recovery",
    cooldownTurns: 8,
  },
  {
    id: "vulnerability",
    name: "Confesión sincera",
    icon: "💧",
    price: 40,
    description: "Le contás algo personal tuyo. Te abrís. Sube química como nada.",
    effect: "+50 química",
    statEffects: { chemistry: 50 },
    consumable: true,
    category: "recovery",
    cooldownTurns: 6,
  },

  // ─── EQUIPAMIENTO (permanentes) ───────────────────────────────
  {
    id: "lingerie",
    name: "Lencería",
    icon: "👙",
    price: 45,
    description: "Sube la temperatura cuando se quita la ropa.",
    effect: "Permanente — bonus narrativo en escenas íntimas",
    statEffects: {},
    consumable: false,
    category: "gear",
    cooldownTurns: 0,
  },
  {
    id: "intimate_toy",
    name: "Juguete íntimo",
    icon: "🪄",
    price: 50,
    description: "Para llevar la escena al siguiente nivel en acto 3.",
    effect: "Permanente — desbloquea acciones explícitas",
    statEffects: {},
    consumable: false,
    category: "gear",
    cooldownTurns: 0,
  },
  {
    id: "condoms",
    name: "Protección",
    icon: "🔒",
    price: 15,
    description: "Lo básico. Sin esto algunas chicas no avanzan.",
    effect: "Permanente — requerido por algunas chicas para acto 3",
    statEffects: {},
    consumable: false,
    category: "gear",
    cooldownTurns: 0,
  },
  {
    id: "hotel_room",
    name: "Cuarto de hotel",
    icon: "🏨",
    price: 70,
    description: "Reserva en un hotel boutique. Cambia de escenario.",
    effect: "Permanente — habilita cambio a espacio privado",
    statEffects: {},
    consumable: false,
    category: "gear",
    cooldownTurns: 0,
  },
  {
    id: "expensive_watch",
    name: "Reloj fino",
    icon: "⌚",
    price: 60,
    description: "Signo de estatus. Funciona con materialistas/sofisticadas.",
    effect: "Permanente — bonus narrativo de atracción",
    statEffects: {},
    consumable: false,
    category: "gear",
    cooldownTurns: 0,
  },
  {
    id: "private_driver",
    name: "Chofer privado",
    icon: "🚗",
    price: 55,
    description: "Te recoge cuando vos digas. Sin esperar Uber.",
    effect: "Permanente — facilita transiciones de escenario",
    statEffects: {},
    consumable: false,
    category: "gear",
    cooldownTurns: 0,
  },
];

export function getItemById(id: string): ShopItem | undefined {
  return SHOP_ITEMS.find((item) => item.id === id);
}
